name: Weather app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project from git
        uses: actions/checkout@v2     

      - name: Build project
        run: |
          yarn
          yarn generate
      - name: Download project as artifact
        uses: actions/upload-artifact@main
        with: 
          name: bundle
          path: dist
